---
- name: Add proxy to access github.com over IPv6
  become: true
  tags: github
  block:
    - name: Add hosts file entries
      blockinfile:
        marker: "# {mark} IPv6 access to github.com"
        path: /etc/hosts
        block: |
          # https://danwin1210.de/github-ipv6-proxy.php
          2a01:4f8:c010:d56::2 github.com
          2a01:4f8:c010:d56::3 api.github.com
          2a01:4f8:c010:d56::4 codeload.github.com
          2a01:4f8:c010:d56::6 ghcr.io
          2a01:4f8:c010:d56::7 pkg.github.com npm.pkg.github.com maven.pkg.github.com nuget.pkg.github.com rubygems.pkg.github.com
          2a01:4f8:c010:d56::8 uploads.github.com
          2606:50c0:8000::133 objects.githubusercontent.com www.objects.githubusercontent.com release-assets.githubusercontent.com gist.githubusercontent.com repository-images.githubusercontent.com camo.githubusercontent.com private-user-images.githubusercontent.com avatars0.githubusercontent.com avatars1.githubusercontent.com avatars2.githubusercontent.com avatars3.githubusercontent.com cloud.githubusercontent.com desktop.githubusercontent.com support.github.com
          2606:50c0:8000::154 support-assets.githubassets.com github.githubassets.com opengraph.githubassets.com github-registry-files.githubusercontent.com github-cloud.githubusercontent.com
        prepend_newline: true
